# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - eshop-cloudx

on:
  push:
    branches:
      - main
    paths:
      - 'src/Web/**'
      - '.github/workflows/main_eshop-cloudx.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build Web project
        run: dotnet build src/Web/Web.csproj --configuration Release

      - name: Publish Web project
        run: dotnet publish src/Web/Web.csproj --configuration Release --output "${{ runner.temp }}/webapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}/webapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D119954E845A4E63A6FCD98A2351BD6A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4209A09120A54FB495381A20245E1BE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0707CBC7DCD04163ACF3798BF038A037 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eshop-cloudx'
          slot-name: 'Production'
          package: .
          